name: Build and Push to Docker Hub

on:
  push:
    branches: 
     - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spam_detection:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/spam_detection:latest
